name: Happy Hour

on:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer'
        required: true
      hours:
        description: 'Hours'
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Customer: ${{ github.event.inputs.customer }}"
        echo "Hour: ${{ github.event.inputs.hours }}"
